name: Run get data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python syncdata.py
        env:
          ANIDB_CLIENT_NAME: ${{ secrets.ANIDB_CLIENT_NAME }}
          ANIMELIST_AUTH: ${{ secrets.ANIMELIST_AUTH }}
      - name: deploy
        shell: bash
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git branch data
          git add -A
          CHANGE_COUNT=$(git status --porcelain | wc -l)
          if [ $CHANGE_COUNT -gt 0 ]
          then
            git commit -m "Update data"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.repository.full_name }}.git data
          else
            echo "No changes"
          fi

