name: Run get data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python syncdata.py
        env:
          ANIDB_CLIENT_NAME: ${{ secrets.ANIDB_CLIENT_NAME }}
          ANIMELIST_AUTH: ${{ secrets.ANIMELIST_AUTH }}
      - name: deploy
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git checkout data || git checkout -b data
          git add -A
          git commit -m "Update data"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.repository.full_name }}.git data

